enum SkillsEnum {
    Python = 'Python',
    Java = 'Java',
    CSharp = 'C#',
    DotNet = '.NET',
    AspNet = 'ASP.NET',
    JavaScript = 'JavaScript',
    TypeScript = 'TypeScript',
    React = 'React',
    NodeJs = 'Node.js',
    SQL = 'SQL',
    NoSQL = 'NoSQL',
    HTML = 'HTML',
    CSS = 'CSS',
    SpringBoot = 'SpringBoot',
    AWS = 'AWS',
    GCP = 'GCP',
    Azure = 'Azure',
    AI = 'AI',
    Git = 'Git',
    Docker = 'Docker',
    Agile = 'Agile',
    Testing = 'Testing',
    UxUi = 'UX/UI',
    Algorithms = 'Algorithms',
    OOP = 'OOP',
    Architecture = 'Architecture',
    Debugging = 'Debugging',
    Other = 'Other',
    AzureDevOps = 'Azure DevOps',
    Security = 'Security',
}

export default SkillsEnum;
